# Site settings
title: M
blog_title: Mikena Wood
header-img: img/home-bg.jpg
email: mikena@woodmail.me
copyright_name: Mikena Wood
description: "Personal Site of Mikena Wood"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: http://mikenawood.com #only used in disque comments for now
disqus_url: mikenawood.com # disque comments are broken if you send http:// along with url
github_username:  mi-wood
twitter_username: donutfemme
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
